multiple repositories, backend update.

diff --git a/yalp b/yalp
--- a/yalp
+++ b/yalp
@@ -2,8 +2,12 @@
 
 # -------------------------
 #      USER SETTINGS
-REPO=https://organized-absorbed-waxflower.glitch.me/yalp
-PKGDIR=$HOME/yalp
+
+REPOS=(
+    "https://yalpsrv.bcreisepic.repl.co/yalp" # The first repository in this list is the default one
+)
+PKGDIR=$HOME/yalp 
+
 #   END OF USER SETTINGS
 # -------------------------
 
@@ -15,12 +19,22 @@ getpkg() {
     mkdir -p $PKGDIR/$1
     cd $PKGDIR/$1
     printf "getting package: $1\n"
-    if curl -sSfO $REPO/pkg/$1.config > /dev/null; then
-        . $PKGDIR/$1/$1.config
-        curl -O $REPO/pkg/$REALNAME
-    else
+    local success=false
+
+    for repo in "${REPOS[@]}"; do
+        if curl -sSfO "$repo/pkg/$1.config" > /dev/null 2<&1; then
+            success=true
+            . $PKGDIR/$1/$1.config
+            curl -O "$repo/pkg/$REALNAME"
+            break
+        else
+            printf "\e[33mWARN:\e[0m The repo '$repo' failed to respond.\n"
+        fi
+    done
+
+    if ! $success; then
+        printf "\e[41mERR:\e[0m Failed to download $1.\n"
         rm -rf $PKGDIR/$1
-        exit 1
     fi
 }
 
@@ -32,31 +46,35 @@ cli_install() {
     done
     for pkg in "${pkgs[@]}"; do
         ADDTOPATH="false" # if this isnt set to anything else at start, some packages will be installed to PATH which arent supposed to for some reason.
-        . $PKGDIR/$pkg/$pkg.config
-        cd $PKGDIR/$pkg
-        printf "\nPerforming install for $pkg...\n"
-        eval "$INSTALL_CMD"
-        if [[ "$ADDTOPATH" == "true" ]]; then
-            if command -v grep >/dev/null 2>&1 && ! echo $PATH | grep -q "$PKGDIR/$pkg"; then
-                if [ -n "$BASH_VERSION" ]; then
-                    echo "export PATH=\"\$PATH:$PKGDIR/$pkg\"" >> "$HOME/.bashrc"
-                    export PATH="$PATH:$PKGDIR/$pkg"
-                elif [ -n "$ZSH_VERSION" ]; then
-                    echo "export PATH=\"\$PATH:$PKGDIR/$pkg\"" >> "$HOME/.zshrc"
-                    export PATH="$PATH:$PKGDIR/$pkg"
+        if [[ -f "$PKGDIR/$pkg/$pkg.config" ]]; then
+            . $PKGDIR/$pkg/$pkg.config
+            cd $PKGDIR/$pkg
+            printf "\nInstalling $pkg...\n"
+            eval "$INSTALL_CMD"
+            if [[ "$ADDTOPATH" == "true" ]]; then # ill make this readable later dw
+                if command -v grep >/dev/null 2>&1 && ! echo $PATH | grep -q "$PKGDIR/$pkg"; then
+                    if [ -n "$BASH_VERSION" ]; then
+                        echo "export PATH=\"\$PATH:$PKGDIR/$pkg\"" >> "$HOME/.bashrc"
+                        export PATH="$PATH:$PKGDIR/$pkg"
+                    elif [ -n "$ZSH_VERSION" ]; then
+                        echo "export PATH=\"\$PATH:$PKGDIR/$pkg\"" >> "$HOME/.zshrc"
+                        export PATH="$PATH:$PKGDIR/$pkg"
+                    fi
                 fi
+                echo Added $pkg to PATH. You might need to restart your shell for $pkg to work.
             fi
-            echo Added $pkg to PATH. You might need to restart your shell for $pkg to work.
-        fi
+        fi 
     done
 }
 cli_remove() {
     for pkg in "$@"; do
+        . $PKGDIR/$pkg/$pkg.config
         rm -rvf $PKGDIR/$pkg
+        eval "$REMOVE_CMD"
     done
 }
 
-YALP_VERSION="0.5.4"
+YALP_VERSION="0.5.5-nightly"
 case "$1" in
     install|i)
         if [ $# -lt 2 ]; then
@@ -83,11 +101,11 @@ case "$1" in
             echo "yalp: missing second argument" >&2
             exit 1
         fi
-        curl -sS $REPO/search?q=$2;;
+        curl -sS $REPOS/search?q=$2;;
     update)
         for f in $(find $PKGDIR -type f -name "*.config"); do
             . $f
-            curl -sS $REPO/pkg/$(basename $f) -o $f.config.new
+            curl -sS $REPOS/pkg/$(basename $f) -o $f.config.new
             OLDPKGVER=$PKGVER
             . $f.config.new
             if [ "$PKGVER" != "$OLDPKGVER" ]; then
@@ -97,7 +115,7 @@ case "$1" in
             rm $f.config.new
         done;;
     *)
-        printf "yalp v$YALP_VERSION\nvariables:\n   REPO: $REPO\n   PKGDIR: $PKGDIR\n\n"
+        printf "yalp v$YALP_VERSION\nvariables:\n   REPO: $REPOS\n   PKGDIR: $PKGDIR\n\n"
         printf "commands:\n   install/i - installs a package\n"
         printf "   uninstall/rm - removes a package\n"
         printf "   run - runs a package (EXEC_CMD from config file)\n"
